# Generated by Django 5.0 on 2025-01-21 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='file',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
    ]
